Vagrant.configure(2) do | config |
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Debian 8
  config.vm.define "debian8" do |tato|
    tato.vm.hostname = "debian8.dev"
    tato.vm.box = "debian/jessie64"
    tato.vm.network :private_network, ip: "192.168.60.2"
    tato.vm.network "forwarded_port", guest: 5050, host: 5151
  end

  # Ubuntu 15.04
  config.vm.define "ubuntu15" do |tato|
    tato.vm.hostname = "ubuntu15.dev"
    tato.vm.box = "ubuntu/vivid64"
    tato.vm.network :private_network, ip: "192.168.60.3"
    tato.vm.network "forwarded_port", guest: 5050, host: 5252
  end

  # CentOS 7
  config.vm.define "centos7" do |tato|
    tato.vm.hostname = "centos7.dev"
    tato.vm.box = "geerlingguy/centos7"
    tato.vm.network :private_network, ip: "192.168.60.4"
    tato.vm.network "forwarded_port", guest: 5050, host: 5353
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "tato_servers" => ["debian8", "ubuntu15", "centos7"],
      "all_groups:children" => ["tato_servers"]
    }

    ansible.sudo = true
    ansible.playbook = "provision.yml"
  end
end
